name: submission_msml

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn

  - pip:
      - mlflow
      - flask
      - joblib
      - docker